apiVersion: v1
kind: Secret
metadata:
  name: creds-github
  annotations:
    tekton.dev/git-0: https://github.com 
type: kubernetes.io/basic-auth
stringData:
  username: <YOUR USER>
  password: <YOUR API TOKEN / PASSWORD>