apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: buildpack-from-git
spec:
  pipelineRef:
    name: buildpack-from-git
  taskRunTemplate:
    serviceAccountName: buildpack-from-git
    podTemplate:
      securityContext:
        fsGroup: 0 ### => !!! Required for Rancher Longhorn !!! 
        runAsUser: 0
        # runAsNonRoot: true  ### => and this must be diabled, if fsGroup is set
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: creds-ghcr-kaniko
  params:
  - name: repo-url
    value: https://github.com/<YOUR REPO>.git
  - name: image-reference
    value: ghcr.io/<YOUR REPO>/<YOUR IMG NAME>:latest